// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace prosjekt_webapp2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241113164449_moreTestfolders1")]
    partial class moreTestfolders1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.35");

            modelBuilder.Entity("ContentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ContentType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentFolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("UserId");

                    b.ToTable("Document");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Hallo,\nDette er en test",
                            ContentTypeId = 1,
                            CreatedDate = new DateTime(2024, 11, 13, 17, 44, 49, 765, DateTimeKind.Local).AddTicks(7631),
                            ParentFolderId = 1,
                            Title = "importante shit",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentFolderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("UserId");

                    b.ToTable("Folder");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "a",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "b",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "c",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Homework",
                            ParentFolderId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Totally_legal_movies:)",
                            ParentFolderId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "great_tits",
                            ParentFolderId = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Homework",
                            ParentFolderId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Homework",
                            ParentFolderId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            Name = "Photos",
                            ParentFolderId = 3,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "a@a.a",
                            Password = "a",
                            Username = "a"
                        },
                        new
                        {
                            Id = 2,
                            Email = "b@b.b",
                            Password = "b",
                            Username = "b"
                        },
                        new
                        {
                            Id = 3,
                            Email = "c@c.c",
                            Password = "c",
                            Username = "c"
                        });
                });

            modelBuilder.Entity("Document", b =>
                {
                    b.HasOne("ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Folder", "ParentFolder")
                        .WithMany()
                        .HasForeignKey("ParentFolderId");

                    b.HasOne("User", "Owner")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("Owner");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("Folder", b =>
                {
                    b.HasOne("Folder", "ParentFolder")
                        .WithMany()
                        .HasForeignKey("ParentFolderId");

                    b.HasOne("User", "Owner")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("ParentFolder");
                });
#pragma warning restore 612, 618
        }
    }
}
